### ISSUE TITLE
是否可以不使用服务器，直接用VLC来播放stream？

### ISSUE THREAD

**Issue by tonyho** [gezhaoyou/RtmpPublishKit#2]
我想测试一下这个apk，希望直接使用VLC来获取手机的推流， 不经过服务器，这个可以实现吗？
如果可以的话，我需要将rmtpUrl改成VLC PC的地址吗？

    private String rtmpUrl = "rtmp://192.168.2.103/live/livedemo";

如果可以的话， VLC这边应该如何来打开这个stream呢？

**Comment by gezhaoyou** [comment]
不可以，必须经过服务器

**Comment by gezhaoyou** [comment]
推荐使用srs，方便简单
